config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' =>  'static_pages#about'
  get 'connect' => 'static_pages#connect'
  get 'news' => 'static_pages#news'
  get 'changetx' => 'static_pages#changetx'
  get 'sigup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' =>'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :account_activations, only:[:edit]
  resources :microposts, only:[:create,:destroy]
  resources :relationships, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page])
  end
end
  def help
  end
  def about

  end
  def connect
  end
  def news

  end
  def changetx

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,"about")%>

<div class=" col-md-8  bg-primary">
</div>
<div class="row">
  <div class="col-md-8 ">
    <div class="row">
      <div class="col-md-offset-2">
        <em><h1>About</h1></em>
        <div>

          <p class="lead text-danger">这个小小的webApp,是我一段时间内自学的成果.</p>
          <p class="text-left">开发环境：<a href="http://www.ubuntu.com/index_kylin">Ubuntu14.04</a></p>
          <p class="text-left">开发工具：<a href="http://www.jetbrains.com/ruby/">Rubymine</a>
            <a href="http://www.jetbrains.com/webstorm/">webStrom</a></p>
          <p class="text-left">后台语言：<a href="http://rubyonrails.org/">Ruby on Rails</a></p>
          <p class="text-left">前端语言：<a href="http://www.apjs.net/">AngularJS</a> </p>
          <p class="text-left">页面布局： <a href="http://www.bootcss.com/">Bootstrap响应式布局</a></p>
          <p class="text-left">版本控制：<a href="http://baike.baidu.com/link?url=2IF5mAz-VnTv--QB8YVDba2NjLG48WXfQ_MraoJGdcMcHJAYA_GZ1uLBkCOHvktIEhK_bBHucG_hvozjI_3mHhxKXLA6XGEPdSEOe6zmGTC">Git</a></p>
          <p class="text-left"> 远程仓库：<a href="https://bitbucket.org/">Bitbucket</a></p>
          <p class="text-left"> 生产环境: <a href="https://dashboard.heroku.com">Heroku</a></p>
          <p class="text-left"></p>
          <p class="lead text-danger">开发过程</p>
          <div class="text-warning texts">
            之前有想过用java的SSH框架来写后台，毕竟之前学了这么久的java，想做点东西来练练手。
            寒假在家开始写的时候发现如果用java写的话，一个人很难在较短时间内完成，并且写的过程
            中有许许多多的问题解决不来。涉及到了框架的底层源码，我决定换一种语言来写，于是我开
            始学Ruby on rails（一门强大的语言）不过国内学习ruby的人很少，资料也不多。
            去图书馆找的最新的还是13年出版的关于ruby1.9，rails3.0版本的，奈何ruby on rails 版本
            不向下兼容，只能学最新版本没办法，在网上买了Ruby最新版本的电子书教程。老外写的，讲的比较深。
          </div>

          <div class="text-warning texts">
            刚开始学习的时候，有许许多多的莫名其妙的开发环境问题
            之前在Windows下连环境都搭建不起来，转到云端开发环境下学习了几天，不过云端开发响应慢，内存小，不流畅。没办法，转到Linux下玩吧，
            刚开始，我是在Windows下用虚拟机装了个Ubuntu系统，很顺利的搭建了rails开发环境。不过不得不吐槽我这渣渣I3笔记本，
            开了虚拟机巨卡，内存直接使用95%，在卡卡的Ubuntu上玩了一个星期，有一次卡死了，我直接关了电源，结果导致了Ubuntu系统直接崩溃，
            虚拟机打不开了，白费我花了几个小时搭建的环境。又得另想办法了。只好清理出一个盘来做压缩卷，
            然后在Windows的基础上装了一个并行的Ubuntu系统，也就是双系统。然后就一直在Ubuntu下开发，顺便学习Linux知识。
            从3.3号开始学习，到现在差不多一个月的时间。对Ruby Rails AngularJS Jquery  Bootstrap都只是入门了而已，并没有深入的学习，
            也是通过写这个APP我才接触到这么多东西，以前只会写点简单的Html PHP。写这个APP我最大的收获就是，知道了自己有太多的东西不懂了，
            知道自己需要更加努力的学习，同时也增强了自己的自学能力。
          </div>
          <p class="lead"><em>2015.3.29</em> </p>

        </div>
      </div>
    </div>
  </div>
</div>

<div class=" col-md-8  bg-primary">
</div>

app/views/static_pages/changetx.html.erb
<%provide(:title,"changetx") %>

<div class="row bg-success" >
  <div class="col-md-10 col-md-offset-1">

    <div id='slider' class='swipe'>
      <div class='swipe-wrap'>

        <div>
          <div class="lead bottomtext">由于本网站的头像关联至gravatar，我们需要登录到gravatar网站进行修改，
            而gravatar被国家防火墙屏蔽了，我们需要翻墙才能登录，下面的教程会教大家怎么翻墙到
            gravatar网站修改头像
          </div>
          <%= link_to image_tag("a1.png",alt: "join us")%>
          <div class="text-danger text-left bottomtext">
            Gravatar是Globally Recognized Avatar的缩写,是gravatar推出的一项服务
            ，意为“全球通用头像”（已被墙）。如果在Gravatar的服务器上放置了你自己
            的头像，那么在任何支持Gravatar的blog或者留言本上留言时，
            只要提供你与这个头像关联的email地址，就能够显示出你的Gravatar头像来

          </div>
        </div>



        <div>
          <div class="lead">第一步：准备翻墙工具VPN；白鸽VPN
            下载地址：<a href="http://bgvpn.cn/">http://bgvpn.cn/</a>
            下载后安装在本地电脑
          </div>
          <%= link_to image_tag("a2.png",alt: "join us")%>
          <div class="text-danger">
            我们利用白鸽VPN提供的新用户注册送1小时体验时间来完成修改头像，当然如果平时我们需要翻墙
            上一些其他网站也可以的，VPN客户端有注册的功能，每次使用时临时注册一个新用户，可以获得一个小时的VPN服务
            或者还可以选择一些其他翻墙方式，例如谷歌GoAgent。
          </div>
        </div>


        <div>
          <div class="lead">
            第二步：  当VPN客户端与服务器连接成功后，我们就可以浏览被防火墙墙的网站了，
            如<a href="www.facebook.com">Facebook</a>;
            <a href="https://www.youtube.com">You to be</a>（全球最大的视频网站）
            当然也可以登录<a href="en.gravatar.coma">gravatar</a>修改头像
          </div>
          <%= link_to image_tag("a3.png",alt: "join us")%>
          <div class="text-danger" >
            登录<a href="en.gravatar.coma">gravatar</a>之后我们需要注册一个账号，Eail就是你在本站注册时使用的Eail
            因为你的头像上传的路径是由你的Eail地址通过哈希算法得到的，本站获取头像就是通过你注册时的Eail的哈希到gravatar
            服务器获取，如果Eail不一致，将获取不到
          </div>
        </div>

        <div>
          <div class="lead">第三步，注册成功之后我们需要上传头像了，头像大小由你自己选择，
            不过本站为了头像统一，对获取的头像做了一些处理，统一为80Px.
          </div>
          <%= link_to image_tag("a4.png",alt: "join us")%>
          <div class="text-danger">
            上传成功之后就可以打开本站的首页看看自己的头像是否变成了你上传在gravatar上的头像
          </div>
        </div>


      </div>
      <div class="slider-control">
        <button type="button" class="btn btn-primary"onclick="mySwipe.prev()">上一步</button>
        <button type="button" class="btn btn-success" onclick="mySwipe.next()">下一步</button>
      </div>
      <script>
          window.mySwipe = Swipe(document.getElementById('slider'));
      </script>
    </div>



  </div>
</div>

app/views/static_pages/connect.html.erb
<% provide(:title,"connect")%>

<div class=" col-md-8  bg-primary">
</div>
<div class="row">
  <div class="col-md-8 ">
    <div class="row">
      <div class="col-md-offset-2">
        <em><h1 class="text-danger">JOIN US</h1></em>
        <div>
          <%= link_to image_tag("joinus.jpg",alt: "join us")%>
        </div>
        <div>
          <p class="text-left text-warning"> QQ: 1243228706</p>
          <p class="text-left text-warning"> Email:1243228706@qq.com</p>
          <p class="text-left text-danger lead">说明:</p>
          <p class="text-left text-warning texts">
            如果你对WEB开发感兴趣，想学习WEB开发方面的知识，欢迎你加入我们，我会把这个网站的
            源码放在GitUP上，你可以联系我获取源代码，然后我们大家一起将这个小小的APP逐渐完善。
            不管你想写前端，还是后台。加入我们，你会学习到怎么通过git进行项目的版本控制，通过gitup的开源服务
            多个人协同开发一个项目，学习到一些最新最前沿的WEB开发技术。如果你还是一个人在闷头自学，毫无头绪，
            不知道方向，加入我们，一起学习，一起进步。通过团队学习，提高学习效率！！
          </p>
        </div>

      </div>
    </div>
  </div>
</div>

<div class=" col-md-8  bg-primary">
</div>

app/views/static_pages/help.html.erb
<% provide(:title,"help")%>

<div class=" col-md-8  bg-primary">
</div>
<div class="row">
  <div class="col-md-8 ">
    <div class="row">
      <div class="col-md-offset-2">
        <em><h1 class="text-danger">Help</h1></em>
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  <p class="text-success">新用户注册</p>
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
              <div class="panel-body">
                <p class="text-left text-warning" >
                  点击首页的Sing up图标，待跳转到注册页面后输入注册信息。
                  用户名长度在5-10位，密码长度为6—10位。Email则填写您常用的Email。
                  信息输入准确后点击立即注册即可完成注册。网页会自动跳转到您的资料页面。

                </p>
              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
              <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                 <p class="text-success">发表微博</p>
                </a>
              </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
              <div class="panel-body">
                <p class="text-left text-warning">
                  登录之后，点击导航栏的首页即可跳转到首页，您可以在首页的文本输入框内输入1000个字符以内的字符，
                  输入框可以上下升缩，您可以通过上下拖动鼠标升缩。当然，您也可以上传图片，大小限制在5M以内，
                  如果超过5M，将会提示错误。上传之后，您可以在首页即时看到您发表的微博，提醒一下，您也可以关注其他用户，
                  当其他用户发表微博的时候，您可以在您的即时的在您首页看到。同样的，如果其他用户关注了您，
                  您发表的微博也会在其他用户首页显示。
                </p>

              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingThree">
              <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                 <p class="text-success">修改头像</p>
                </a>
              </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
              <div class="panel-body">
                <p class="text-left text-warning">
                登录之后，点击帐号管理的下拉菜单，选择修改头像，将会看到修改头像的详细教程。
                您照着教程就可以完成修改头像功能。如果遇到什么问题，你也可以联系我们解决
                </p>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

<div class=" col-md-8  bg-primary">
</div>

app/views/static_pages/home.html.erb
<%provide(:title,"home") %>
<div class="center jumbotron">

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info'%>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form'%>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>
        Micropost Feed
      </h3>
      <%= render 'shared/feed' %>
    </div>

  </div>

<% else %>


<h1>Welcome to the BAJOROR</h1>
<h2>
  this is the home page for
  <a href="#">BAJOROR</a>
  please click the button to sing up
</h2>
  <%= link_to "sing up now!", sigup_path, class: "btn btn-lg btn-primary" %>
  </div>
<%= link_to image_tag("rails.jpg",alt: "Rails logo"),
                        'http://rubyonrails.org'   %>
<p class="text-primary">
    点击右上角的帮助页面获取更多信息
</p>

  <% end %>

app/views/static_pages/news.html.erb
<%provide(:title,"news") %>
<div class=" col-md-8  bg-primary">
</div>
<div class="row">
  <div class="col-md-8 ">
    <div class="row">
      <div class="col-md-offset-2">
        <em><h1 class="text-danger">通知</h1></em>
        <div class="text-warning text-left">
          版本：1.0.0
          暂无升级通知
        </div>

      </div>
    </div>
  </div>
</div>

<div class=" col-md-8  bg-primary">
</div>