config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' =>  'static_pages#about'
  get 'connect' => 'static_pages#connect'
  get 'news' => 'static_pages#news'
  get 'changetx' => 'static_pages#changetx'
  get 'sigup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' =>'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :account_activations, only:[:edit]
  resources :microposts, only:[:create,:destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer  class="footer">
  <small>
    <a href="http://rubyonrails.org/">Ruby on Rails  </a>
    <a href="http://www.bootcss.com/">Bootstrap  </a>
    <a href="http://www.apjs.net/">AngularJS </a>
  </small>
  <nav>
    <ul>
    <li><%= link_to "关于" ,about_path%></li>
    <li><%= link_to "加入我们" ,connect_path%></li>
    <li><%= link_to "通知" ,news_path%></li>

    </ul>

  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "BAJOROR",root_path,id: "logo"%>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "首页" , root_path%></li>
        <li><%= link_to "帮助" , help_path%></li>
        <% if logged_in? %>
            <li><%= link_to "所有用户" ,users_path%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                帐号管理<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "我的资料" ,current_user %></li>
                <li><%= link_to "修改头像" ,changetx_path%></li>
                <li class="divider"></li>
                <li>
                  <%=link_to "退出",logout_path,method: "delete" %>
                </li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to "登录" ,login_path%></li>
            <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">

</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%=render 'layouts/shim' %>

<body>
<%= render 'layouts/header'%>

<div class="container">
<% flash.each do |message_type,message| %>
  <div class="alert alert-<%= message_type%>">
    <%= message %>
  </div>
      <% end %>
  <%= yield %>
  <%= render 'layouts/footer'%>
 <!-- <%= debug(params) if Rails.env.development?%>-->
</div>


</body>
</html>